# Generated by Django 6.0.7 on 2026-07-08 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('email', 'Email Account'), ('apple_id', 'Apple ID'), ('icloud', 'iCloud'), ('banking', 'Banking Account'), ('social', 'Social Media')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=200)),
                ('status', models.CharField(default='Protected', max_length=20)),
                ('security_recommendation', models.TextField(blank=True)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protected_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('details', models.TextField()),
                ('severity', models.CharField(default='info', max_length=20)),
                ('source', models.CharField(default='System', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
