# Generated by Django 6.0.7 on 2026-08-06 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_otp_code_profile_otp_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Login Success'), ('failed_login', 'Failed Login'), ('suspicious_activity', 'Suspicious Activity'), ('account_created', 'Account Created'), ('password_changed', 'Password Changed'), ('security_scan', 'Security Scan'), ('suspicious_link', 'Suspicious Link'), ('application_error', 'Application Error')], max_length=30),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='severity',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20),
        ),
    ]
