# Generated by Django 6.0.7 on 2026-07-08 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_time_protection', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('dark_mode', models.BooleanField(default=True)),
                ('language', models.CharField(default='en', max_length=20)),
                ('security_preferences', models.TextField(blank=True, default='MFA, phishing monitoring, password health')),
                ('scan_frequency', models.CharField(default='daily', max_length=20)),
                ('notification_preferences', models.TextField(blank=True, default='threats, scans, reports')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
