# Generated by Django 6.0.7 on 2026-08-05 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_securitylog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SecurityLog',
        ),
    ]
