# Generated by Django 6.0.7 on 2026-07-08 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('risk_level', models.CharField(max_length=20)),
                ('is_safe', models.BooleanField(default=True)),
                ('reputation', models.CharField(max_length=20)),
                ('ssl_status', models.CharField(max_length=50)),
                ('reasons', models.TextField(blank=True)),
                ('scan_summary', models.TextField(blank=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
